// Ruuvitag settings
module.exports = {
	RUUVITAG: 1,
    RUUVITAG_LOC_OUTSIDE: 1,
    RUUVITAG_LOC_INSIDE_1: 2,
    RUUVITAG_LOC_INSIDE_2: 3,
    RUUVITAG_LOC_UNKNOWN: 256,
    RUUVITAG_SUPERVISION_TIME: 11*60*1000 /* 11 minutes  */  
}